data_type: "tahoe"
data_name: "clonidine100D"
accelerator: "gpu"
hidden_dims_geopath: [1024, 1024, 1024]
hidden_dims_flow: [1024, 1024, 1024]
hidden_dims_growth: [1024, 1024, 1024]
dim: 100
t_exclude: []
time_geopath: true
whiten: false
velocity_metric: "rbf"
metric_patience: 25
patience: 25
n_centers: 300
kappa: 2
rho: -2.75
alpha_metric: 1
metric_epochs: 100
branchsbm: true
seeds: [42]
branches: 2
metric_clusters: 3